src/PaginaPerfil_V1_net_4_6/Models/PaginaPerfil_V1_net_4_6Context.cs
using Microsoft.Data.Entity;
using PaginaPerfil_V1_net_4_6.Modelo;

namespace PaginaPerfil_V1_net_4_6.Models
{
    public class PaginaPerfil_V1_net_4_6Context : DbContext
    {
        private static bool _created = false;

        public PaginaPerfil_V1_net_4_6Context()
        {
            if (!_created)
            {
                _created = true;
                Database.EnsureCreated();
            }
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
        }

        public DbSet<Contacto> Contacto { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Maps> Maps { get; set; }
    }
}

src/PaginaPerfil_V1_net_4_6/Controllers/ContactoesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using PaginaPerfil_V1_net_4_6.Modelo;
using PaginaPerfil_V1_net_4_6.Models;
using System.Collections.Generic;
using System.Net;
using System;

namespace PaginaPerfil_V1_net_4_6.Controllers
{
    public class ContactoesController : Controller
    {
        private PaginaPerfil_V1_net_4_6Context _context;

        public ContactoesController(PaginaPerfil_V1_net_4_6Context context)
        {
            _context = context;    
        }

        // GET: Contactoes
        public IActionResult Index()
        {
            List<ListContactos> cnt = new List<ListContactos>();

            foreach (Contacto cn in _context.Contacto.ToList())
            {
                ListContactos lt = new ListContactos();
                lt.Id = cn.Id;
                lt.Nombre = cn.Nombre;
                lt.Apellido = cn.Apellido;
                //lt.Ciudad = _context.Ciudad.First(y => y.Id == cn.Id).Nombre;
                cnt.Add(lt);                
            }

            //return View(_context.Contacto.ToList());
            return View(cnt);
        }

        // GET: Contactoes/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Contacto contacto = _context.Contacto.Single(m => m.Id == id);
            if (contacto == null)
            {
                return HttpNotFound();
            }

            return View(contacto);
        }

        // GET: Contactoes/Create
        public IActionResult Enviar()
        {
            return View();
        }

        // POST: Contactoes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Enviar(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _context.Contacto.Add(contacto);
                _context.SaveChanges();

                if (contacto.Email != null)
                {
                    //EnviarMail(contacto.Email);
                }

                return RedirectToAction("Index");
            }
            return View(contacto);
        }

        // GET: Contactoes/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Contacto contacto = _context.Contacto.Single(m => m.Id == id);
            if (contacto == null)
            {
                return HttpNotFound();
            }
            return View(contacto);
        }

        // POST: Contactoes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _context.Update(contacto);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contacto);
        }

        // GET: Contactoes/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Contacto contacto = _context.Contacto.Single(m => m.Id == id);
            if (contacto == null)
            {
                return HttpNotFound();
            }

            return View(contacto);
        }

        // POST: Contactoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Contacto contacto = _context.Contacto.Single(m => m.Id == id);
            _context.Contacto.Remove(contacto);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
                
               
    }

    
}

src/PaginaPerfil_V1_net_4_6/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace PaginaPerfil_V1_net_4_6.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Descripcion 'Acerca de'.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Descricpion 'Contact'.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/PaginaPerfil_V1_net_4_6/Controllers/MapsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using PaginaPerfil_V1_net_4_6.Modelo;
using PaginaPerfil_V1_net_4_6.Models;

namespace PaginaPerfil_V1_net_4_6.Controllers
{
    public class MapsController : Controller
    {
       
        // GET: Maps
        public IActionResult Index()
        {
            ViewData["Message"] = "Este es un mapa creado con la API de Google";
            return View();
        }

      
    }
}

src/PaginaPerfil_V1_net_4_6/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace PaginaPerfil_V1_net_4_6.Controllers
{
    public class PieController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/PaginaPerfil_V1_net_4_6/Views/Contactoes/Delete.cshtml
@model PaginaPerfil_V1_net_4_6.Modelo.Contacto

@{
    ViewData["Title"] = "Eliminar";
    Layout = "_OnePage";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contacto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/PaginaPerfil_V1_net_4_6/Views/Contactoes/Details.cshtml
@model PaginaPerfil_V1_net_4_6.Modelo.Contacto

@{
    ViewData["Title"] = "Detalles";
    Layout = "_OnePage";
}

<h2>Details</h2>

<div>
    <h4>Contacto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/PaginaPerfil_V1_net_4_6/Views/Contactoes/Edit.cshtml
@model PaginaPerfil_V1_net_4_6.Modelo.Contacto

@{
    ViewData["Title"] = "Editar";
    Layout = "_OnePage";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Contacto</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Apellido" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Ciudad" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Ciudad" class="form-control" />
                <span asp-validation-for="Ciudad" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Nombre" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/PaginaPerfil_V1_net_4_6/Views/Contactoes/Enviar.cshtml
@model PaginaPerfil_V1_net_4_6.Modelo.Contacto

@{
    ViewData["Title"] = "Ponte en contacto";
    Layout = "_OnePage";
}

<section id="contact">
    <div class="container">
        <div class="row">
            <h1 class="section-heading text-center white">Ponte en contacto...</h1>
            <div class="col-md-7">
                <form asp-action="Create" class="form-horizontal form-control-wrapper">
                    <div class="form-horizontal">
                        
                        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            
                            <div class="col-md-10">
                                <input asp-for="Nombre" placeholder="Nombre" type="text" value="" required />
                                <span asp-validation-for="Nombre" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                          
                            <div class="col-md-10">
                                <input asp-for="Apellido" placeholder="Apellido" type="text" value="" required/>
                                <span asp-validation-for="Apellido" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                         
                            <div class="col-md-10">
                                <input asp-for="Ciudad" placeholder="Ciudad" type="text" value="" required/>
                                <span asp-validation-for="Ciudad" class="text-danger" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <input asp-for="Email" placeholder="Email" type="email" value="" required />
                                <span asp-validation-for="Email" class="text-danger" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <input asp-for="Mensaje" placeholder="Mensaje" type="text" value="" required />
                                <span asp-validation-for="Mensaje" class="text-danger" />
                            </div>
                        </div>
                       
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Enviar"  class="btn btn-primary submit-button" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-5 contact-right">
                <p class="lead white"><i class="fa fa-home contact-icon"></i>Bogota, Carrera 8f #166-74 Int 10 Apto 201</p>
                <p class="lead white"><i class="fa fa-phone"></i>311 652 05 74</p>
                <p class="lead"><i class="fa fa-envelope"></i><a class="white" href="mailto:breinergonza@hotmail.com">breinergonza@hotmail.com</a></p>
            </div>
        </div>
        <div class="social">
            <div class="follow-us">
                <a href="https://www.facebook.com/" class="" target="_blank">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="https://twitter.com/" class="" target="_blank">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="http://instagram.com/" class="" target="_blank">
                    <i class="fa fa-instagram"></i>
                </a>
            </div>
        </div>
        <div class="row">
            <p class="text-center copyright white">@DateTime.Now.Year - Breiner Gonzalez.</p>
        </div>
    </div>
</section>



<div>
    <a asp-action="Index">Back to List</a>
</div>

src/PaginaPerfil_V1_net_4_6/Views/Contactoes/Index.cshtml
@model IEnumerable<PaginaPerfil_V1_net_4_6.Modelo.ListContactos>

@{
    ViewData["Title"] = "Contacto";
    Layout = "_OnePage";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Agregar contacto</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ciudad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ciudad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Detalle</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
        </td>
    </tr>
}
</table>

src/PaginaPerfil_V1_net_4_6/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/PaginaPerfil_V1_net_4_6/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/PaginaPerfil_V1_net_4_6/Views/Maps/Index.cshtml
@{
    ViewData["Title"] = "Sedes";
    Layout = "_OnePage";
}


<br />

<header>

    <div class="row">
        <div class="text-center">
            <h1 class="section-heading">Sedes</h1>
        </div>
    </div>
    <iframe src="https://www.google.com/maps/d/u/1/embed?mid=1FQto2cjW0sPoXt07pwPqBzPxEGI" width="100%" height="500"></iframe>


    </header>

src/PaginaPerfil_V1_net_4_6/Views/Pie/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Pie";
}

src/PaginaPerfil_V1_net_4_6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Breiner Gonzalez</title>
    
    <environment names="Development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/font-awesome/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/adonis.min.css" type="text/css">

        <link href="~/css/normalize.css" rel="stylesheet" />
        <link href="~/css/font-awesome.min.css" rel="stylesheet" />

        <link href="~/css/video.css" rel="stylesheet" />

        <link href='http://fonts.googleapis.com/css?family=Tangerine|Sintony:400,700' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,thin,light&amp;lang=en" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>              
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

  

</head>
<body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand page-scroll" href="#page-top">Adonis</a> -->
                <!-- Replace With Your Logo -->
                <a class="navbar-brand navbar-logo page-scroll" href="#page-top">
                    <img src="~/img/logo.png" alt="Logo">
                </a>
            </div>

            <!-- Main Navigation -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#page-top">Inicio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Servicios</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#scroll">Herramientas</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about-us">Moviles</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#our-work">Tecnologias</a>
                    </li>
                    <li>
                        <a asp-controller="Maps" asp-action="Index">Sedes</a>
                    </li>
                    <li>
                        <a class="page-scroll" asp-controller="Contactoes" asp-action="Enviar">Escribeme</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


    @RenderBody()

    <hr />

    <section>
        <div class="container">
            <div class="row">
                <div >
                    <p class="text-center copyright Black">@DateTime.Now.Year - Breiner Gonzalez.</p>
                </div>
            </div>
        </div>
    </section>

        

    <environment names="Development">
        <script src="~/js/jquery.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/jquery.easing.min.js"></script>
        <script src="~/js/adonis.min.js"></script>

        <script src="~/js/video.js"></script>

        <script type="text/javascript" src="~/js/bootstrap-modal.js"></script>
        <script type="text/javascript" src="~/js/config.js"></script>
        <script type="text/javascript" src="~/js/jquery.bpopup.min.js"></script>
        <script type="text/javascript" src="~/js/jquery.cycle.all.js"></script>
        <script type="text/javascript" src="~/js/jquery.easing-1.3.pack.js"></script>
        <script type="text/javascript" src="~/js/jquery.isotope.min.js"></script>
        <script type="text/javascript" src="~/js/jquery.nicescroll.min.js"></script>
        <script type="text/javascript" src="~/js/jquery.parallax-1.1.3.js"></script>
        <script type="text/javascript" src="~/js/jquery.validate.min.js"></script>
        <script type="text/javascript" src="~/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="~/js/jquery-countto.js"></script>
        <script type="text/javascript" src="~/js/modernizr.js"></script>
        <script type="text/javascript" src="~/js/piebar.js"></script>
        <script type="text/javascript" src="~/js/retina-1.1.0.min.js"></script>
        <script type="text/javascript" src="~/js/script.js"></script>
        <script type="text/javascript" src="~/js/smoothscroll.js"></script>

        <script type="text/javascript" src="~/js/jquery.sticky.js"></script>
        <script type="text/javascript" src="~/js/jquery.appear.js"></script>
        <script type="text/javascript" src="~/js/jquery.maximage.js"></script>
        <script type="text/javascript" src="~/js/jquery-countTo.js"></script>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

    

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/PaginaPerfil_V1_net_4_6/Views/Shared/_OnePage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Breiner Gonzalez</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/font-awesome/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/adonis.min.css" type="text/css">

        <link href="~/css/video.css" rel="stylesheet" />

        <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,thin,light&amp;lang=en" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>



</head>
<body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand page-scroll" href="#page-top">Adonis</a> -->
                <!-- Replace With Your Logo -->
                <a class="navbar-brand navbar-logo page-scroll" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo.png" alt="Logo">
                </a>
            </div>

            <!-- Main Navigation -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">                   
                    <li>
                        <a asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    <li>
                        <a class="page-scroll" asp-controller="Contactoes" asp-action="Enviar">Contactanos</a>
                    </li>
                    <li>
                        <a asp-controller="Contactoes" asp-action="Index">Lista de contactos</a>
                    </li>
                    <li>
                        <a asp-controller="Maps" asp-action="Index">Sedes</a>
                    </li>                   
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


    @RenderBody()

    <!-- Back to top -->
    <a href="#" id="back-top"><i class="fa fa-angle-up fa-2x"></i></a>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Breiner Gonzalez</p>
    </footer>

    <environment names="Development">
        <script src="~/js/jquery.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/jquery.easing.min.js"></script>
        <script src="~/js/adonis.min.js"></script>

        <script src="~/js/video.js"></script>

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>